version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - 8000:8000
    healthcheck:
      interval: 30s
      retries: 5
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8000/
    
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
    healthcheck:
      interval: 30s
      retries: 5
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:3000/
    
